@if($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<div class="row g-3">
 <div class="col-md-8"><label class="form-label" for="name">Nombre del tour *</label><input class="form-control" id="name" name="name" value="{{ old('name',$tour->name??'') }}" required></div>
 <div class="col-md-2"><label class="form-label" for="price">Precio participante *</label><input type="number" min="0" step="0.01" class="form-control" id="price" name="price" value="{{ old('price',$tour->price??'') }}" required></div>
 <div class="col-md-2"><label class="form-label" for="accompanist_price">Precio acompañante *</label><input type="number" min="0" step="0.01" class="form-control" id="accompanist_price" name="accompanist_price" value="{{ old('accompanist_price',$tour->accompanist_price??'') }}" required></div>
 <div class="col-12"><label class="form-label" for="description">Descripción</label><textarea class="form-control" id="description" name="description" rows="3">{{ old('description',$tour->description??'') }}</textarea></div>
 <div class="col-md-3"><label class="form-label" for="tour_date">Fecha</label><input type="date" class="form-control" id="tour_date" name="tour_date" value="{{ old('tour_date',isset($tour)&&$tour->tour_date?$tour->tour_date->format('Y-m-d'):'') }}"></div>
 <div class="col-md-2"><label class="form-label" for="start_time">Inicio</label><input type="time" class="form-control" id="start_time" name="start_time" value="{{ old('start_time',isset($tour)?substr((string)$tour->start_time,0,5):'') }}"></div>
 <div class="col-md-2"><label class="form-label" for="end_time">Término</label><input type="time" class="form-control" id="end_time" name="end_time" value="{{ old('end_time',isset($tour)?substr((string)$tour->end_time,0,5):'') }}"></div>
 <div class="col-md-5"><label class="form-label" for="meeting_point">Punto de encuentro</label><input class="form-control" id="meeting_point" name="meeting_point" value="{{ old('meeting_point',$tour->meeting_point??'') }}"></div>
 <div class="col-md-6"><label class="form-label" for="capacity">Cupos totales</label><input type="number" min="1" class="form-control" id="capacity" name="capacity" value="{{ old('capacity',$tour->capacity??'') }}" placeholder="Sin límite"><small class="text-muted">Participante y acompañante consumen un cupo cada uno.</small></div>
 <div class="col-md-6"><label class="form-label" for="status">Estado *</label><select class="form-select" id="status" name="status"><option value="active" @if(old('status',$tour->status??'active')==='active') selected @endif>Activo</option><option value="inactive" @if(old('status',$tour->status??'active')==='inactive') selected @endif>Inactivo</option></select></div>
</div>
